customhost = "employee.cfkfdd5jhmkt.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chuweizheng-employee"
customregion = "us-east-1"
